spring:
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: 
            client-secret:


  data:
    cassandra:
      keyspace-name: main
      username:
      password: 
      schema-action: recreate-drop-unused
      request:
        timeout: 10s
      connection:
        connect-timeout: 10s
        init-query-timeout: 10s

astra.db:
    id: 
    region: 
    keyspace: main
    application.token: AstraCS:HydapeymAxzIdHwKCdwuvQvT:69da308b4c9daa1e9ed77dc2d74d5c76eda6001f3a5815d2ae5e6473998931bd


datastax.astra:
   secure-connect-bundle: secure-connect-inbox-app.zip
